# .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  # ref: https://github.com/rails/rails/blob/master/.rubocop.yml
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'railties/test/fixtures/tmp/**/*'
    - 'node_modules/**/*'

Performance:
  Exclude:
    - '**/test/**/*'

AsciiComments:
  Enabled: false

Rails:
  Enabled: true

Style/ExpandPathArguments:
  Exclude:
    - 'bin/**'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - 'actionview/test/**/*.builder'
    - 'actionview/test/**/*.ruby'
    - 'actionpack/test/**/*.builder'
    - 'actionpack/test/**/*.ruby'
    - 'activestorage/db/migrate/**/*.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

inherit_from: .rubocop_todo.yml