# inherit_from: .rubocop_todo.yml

# .rubocop.yml
Rails:
  Enabled: true
Style/AsciiComments:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  RubyInterpreters:
    - ruby
    - macruby
    - rake
    - jruby
    - rbx
  Include:
# from default.yml
    - '**/*.rb'
    - '**/*.arb'
    - '**/*.axlsx'
    - '**/*.builder'
    - '**/*.fcgi'
    - '**/*.gemspec'
    - '**/*.god'
    - '**/*.jb'
    - '**/*.jbuilder'
    - '**/*.mspec'
    - '**/*.opal'
    - '**/*.pluginspec'
    - '**/*.podspec'
    - '**/*.rabl'
    - '**/*.rake'
    - '**/*.rbuild'
    - '**/*.rbw'
    - '**/*.rbx'
    - '**/*.ru'
    - '**/*.ruby'
    - '**/*.spec'
    - '**/*.thor'
    - '**/*.watchr'
    - '**/.irbrc'
    - '**/.pryrc'
    - '**/buildfile'
    - '**/config.ru'
    - '**/Appraisals'
    - '**/Berksfile'
    - '**/Brewfile'
    - '**/Buildfile'
    - '**/Capfile'
    - '**/Cheffile'
    - '**/Dangerfile'
    - '**/Deliverfile'
    - '**/Fastfile'
    - '**/*Fastfile'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Jarfile'
    - '**/Mavenfile'
    - '**/Podfile'
    - '**/Puppetfile'
    - '**/Rakefile'
    - '**/Snapfile'
    - '**/Thorfile'
    - '**/Vagabondfile'
    - '**/Vagrantfile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '.bundle/**/*'
    - '.vscode/**/*'
    - 'misc/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
# from default.yml
    - 'node_modules/**/*'
    - 'vendor/**/*'
Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  Enabled: false
Style/ExpandPathArguments:
  Exclude:
    - 'bin/**'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**'
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'
