version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mysecretpassword
    ports:
      - 3000:3000
    volumes:
      - .:/workdir
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
